FROM node:22-alpine AS builder

WORKDIR /app

# install deps and build
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine

# copy built assets
COPY --from=builder /app/dist /usr/share/nginx/html

# custom nginx to serve SPA and proxy API/websocket requests to backend service
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

