FROM node:22-alpine

WORKDIR /app

# use polling for some FS watchers in containers
ENV CHOKIDAR_USEPOLLING=true

COPY package*.json ./
RUN npm install --silent

# copy source
COPY . .

EXPOSE 5173

# start vite dev server bound to 0.0.0.0
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
