# name of the service for vps devOFF
name: Deploy to AWS EC2 INSTANCE

# when code is pushed -> bash the script pipeline to access the remote server and build composed project there
on:
  push:
    branches:
      - main

# what job this script would do
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Execute shh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/BLOG-WEB-GO-FS-APP
            git pull origin main
            docker compose up -d --build
